#
# /etc/pacman.conf — artix-cs2-arena
#

[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
Color
VerbosePkgLists
ParallelDownloads = 5

SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

# Artix repositories
[system]
Include = /etc/pacman.d/mirrorlist

[world]
Include = /etc/pacman.d/mirrorlist

[galaxy]
Include = /etc/pacman.d/mirrorlist

[lib32]
Include = /etc/pacman.d/mirrorlist

# CachyOS repository — for linux-cachyos-bore kernel
[cachyos]
SigLevel = Never
Server = https://mirror.cachyos.org/$repo/$arch
