# User creation
defaultGroups:
  - name: users
  - name: audio
  - name: video
  - name: storage
  - name: lp
  - name: optical
  - name: network
  - name: wheel
  - name: games
  - name: input
  - name: plugdev
  - name: realtime

autologinGroup: autologin
doAutologin: true

sudoersGroup: wheel

setRootPassword: true

passwordRequirements:
  nonempty: true
  minLength: -1

userShell: /bin/bash
