# Welcome module
showSupportUrl: false
showKnownIssuesUrl: false
showReleaseNotesUrl: false

requirements:
  requiredStorage: 40
  requiredRam: 4.0
  internetCheckUrl: "http://example.com"
  check:
    - storage
    - ram
    - root
