efi:
    mountPoint:         "/boot/efi"
    recommendedSize:    512MiB
    minimumSize:        256MiB
    label:              "EFI"

userSwapChoices:
    - none

swapPartitionName:      swap

luksGeneration: luks1

drawNestedPartitions:   true

alwaysShowPartitionLabels: true

initialPartitioningChoice: none
initialSwapChoice: none

defaultPartitionTableType: gpt

requiredPartitionTableType:
    - gpt

defaultFileSystemType:  "xfs"
availableFileSystemTypes:  ["xfs","ext4","btrfs","f2fs"]
