#
# /etc/pacman.conf — artix-cs2-arena
#

[options]
HoldPkg = pacman glibc
Architecture = auto
CheckSpace
Color
VerbosePkgLists
ParallelDownloads = 5

# Artix repositories
system
world
galaxy
lib32

# CachyOS repository — for linux-cachyos-bore kernel
# Enabled for kernel switching after installation
[cachyos]
SigLevel = Never
Server = https://mirror.cachyos.org/$repo/$arch
